### PR TITLE
Improved typing

### PR DESCRIPTION
**Pull request by SamMousa**
This PR improves typing and fixes issues identified by phpstan.
It also removes some functions that were already marked as `@internal` (so it doesn't count as breaking backward compatibility)

### CODE REVIEW

**Comment by boboldehampsink** [comment]
This is breaking the implementation in Craft CMS's test class, as the Yii2 Module now is a "final" class? This is not really BC-compatible. If intended, it should atleast be a new version?

**Comment by SamMousa** [comment]
You are right, changing classes to final should have been a major version update.

**Comment by boboldehampsink** [comment]
Tagging @brandonkelly, which has code that extends this module: https://github.com/craftcms/cms/blob/5.x/src/test/Craft.php

**Comment by boboldehampsink** [comment]
> Un-finalized the module in `master`. Anything else?

I haven't tested it any further, will do tomorrow.

**Comment by boboldehampsink** [comment]
@brandonkelly the latest release of this module results in the following:

```
PHP Fatal error:  Declaration of craft\test\CraftConnector::startApp(?yii\log\Logger $logger = null) must be compatible with Codeception\Lib\Connector\Yii2::startApp(?yii\log\Logger $logger = null): void in /app/user/vendor/craftcms/cms/src/test/CraftConnector.php on line 135
```

Types need to be updated accordingly in Craft as well

**Comment by SamMousa** [comment]
Is the inheritance really needed? Why not use composition?

**Comment by boboldehampsink** [comment]
This would be something for the Craft team to consider. To get some insight, here is how they are using this module: https://github.com/craftcms/cms/tree/5.x/src/test

By the way, I think even changing typing like this is worth a new major release, as its still not backward compatible.

**Comment by SamMousa** [comment]
> This would be something for the Craft team to consider. To get some insight, here is how they are using this module: https://github.com/craftcms/cms/tree/5.x/src/test
> 
> By the way, I think even changing typing like this is worth a new major release, as its still not backward compatible.

I agree, it was a mistake by me, which is why we reverted. Itll be in a major version bump.

**Comment by boboldehampsink** [comment]
> @boboldehampsink We updated the return type for `CraftConnector::startApp()` in Craft 5.5.6.

Thanks! Any chance of a backport for v4 as well?

**Comment by brandonkelly** [comment]
@boboldehampsink We didn’t override that method until Craft 5. And Craft 4 is stuck on codeception/module-yii2 1.1.5, as 1.1.6 is when they started requiring Codeception 5.

If you’re using Codeception 5 with Craft 4, please PR whatever changes you need to Craft. Assuming they don’t break our own tests, we can pull them in.

**Comment by boboldehampsink** [comment]
@brandonkelly we're using Codeception 5 with Craft 4 indeed. That would just be the same fix, correct?

**Comment by brandonkelly** [comment]
As I said, we weren’t overriding that method until Craft 5.

**Pull request merged**
