### PR TITLE
Codeception documentation specified this is true

### PR DESCRIPTION
**Pull request by SaloEater**
https://codeception.com/docs/modules/Yii2
`transaction - (default: true) `

### CODE REVIEW

**Comment by SamMousa** [comment]
LGTM

**Comment by SamMousa** [comment]
Thanks!

**Comment by Naktibalda** [comment]
I wonder if it had to be a documentation fix instead, this is a breaking change for some users.

#14

**Comment by SamMousa** [comment]
In hindsight you are 100% right.

**Comment by SaloEater** [comment]
> I wonder if it had to be a documentation fix instead, this is a breaking change for some users.
> 
> #14

To be honest, if someone writes non-transactional test then he almost 100% has errors in his code.

**Comment by SamMousa** [comment]
No that's not true. It might not be independent and well structured, but it is no indicator for errors...

**Comment by Naktibalda** [comment]
@SamMousa It isn't too late to change default value to `false` and document it.

**Comment by SamMousa** [comment]
That's true, also fine with me.

**Comment by Naktibalda** [comment]
I looked at the code and there was code which set `transaction` to the same value as `cleanup` if transaction wasn't set, and `cleanup` is set to `true` by default, so this change only made difference for users who had `cleanup: false` and no `transaction` setting in their configuration.

https://github.com/Codeception/module-yii2/blob/1802a03cdc3b01bb6cd818a5a81979bac16cad27/src/Codeception/Module/Yii2.php#L229-L230

**Pull request merged**
