### PR TITLE
Adding log from Yii to artifacts when test fails

### PR DESCRIPTION
**Pull request by aywan**

### CODE REVIEW

**Comment by SamMousa** [comment]
I'm going to close & reopen this. Hopefully it will then allow the new CI to run properly!

**Comment by aywan** [comment]
I will try to fix tests soon

**Comment by samdark** [comment]
@aywan would you please merge master into the PR branch. Tests are now in order with GitHub actions in place.

**Comment by SamMousa** [comment]
This breaks BC, since the nullable argument is not optional.
Other than that I like the idea

**Comment by aywan** [comment]
Why tests are in external repo?

**Comment by SamMousa** [comment]
Because the module wasn't, originally.. Since codeception modules have been split to separate repos, we could merge the tests back into this one.

**Comment by DBX12** [comment]
Off-topic for this pull request: I would really like to see the tests in the module repo as well. It was confusing to clone the repo and see no tests folder the first time :D

**Comment by SamMousa** [comment]
A PR moving them would be greatly appreciated!

**Comment by samdark** [comment]
So now tests are moved.

**Comment by developedsoftware** [comment]
Can this be merged?

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
