### PR TITLE
PHP 8.1: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated

### PR DESCRIPTION
**Pull request by uaoleg**

### CODE REVIEW

**Comment by SamMousa** [comment]
Why not fix the type on the assign? Now it is done twice

**Comment by uaoleg** [comment]
> Why not fix the type on the assign? Now it is done twice

Because after assign we have criterias like `$queryString === null`

**Review by Arhell — COMMENTED** [review]
@samdark

**Review by samdark — APPROVED** [review]
Looks OK.

**Comment by uaoleg** [comment]
@SamMousa can we merge it please?

**Comment by uaoleg** [comment]
@SamMousa @Arhell can we merge it please?

**Comment by acorncom** [comment]
Is there someone who can release this? Not urgent, but it's throwing a few wrinkles in a PHP 8.1 upgrade on our end 😄

**Comment by acorncom** [comment]
For future travelers, this was released in `1.1.8`

**Pull request merged**
